"""Circular ingestion.

Turns raw circular text into obligation-bearing sentences. There is no live
SEBI circular feed wired in here — the corpus below is a small set of
synthetic, clearly-fictional circulars written for this demo, not scraped
or reproduced from real SEBI documents. See README's honesty table.
"""
from __future__ import annotations

import re
from typing import Protocol

from regsense.domain.models import Circular

OBLIGATION_MARKERS = (
    "shall",
    "must",
    "is required to",
    "are required to",
    "is mandated to",
    "needs to",
    "shall not",
)

_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+")


def split_sentences(text: str) -> list[str]:
    return [s.strip() for s in _SENTENCE_SPLIT_RE.split(text.strip()) if s.strip()]


def extract_obligations(text: str) -> tuple[str, ...]:
    """A sentence counts as an obligation if it contains one of the
    OBLIGATION_MARKERS. This is a deliberately simple heuristic — see
    README for what a production version needs instead (NER over
    regulatory language, not keyword matching)."""
    sentences = split_sentences(text)
    return tuple(
        s for s in sentences if any(marker in s.lower() for marker in OBLIGATION_MARKERS)
    )


class CircularSource(Protocol):
    """Interface a real circular feed (SEBI API scraper, email parser,
    document upload) would implement to replace SyntheticCircularSource."""

    def fetch(self) -> tuple[dict, ...]: ...


class SyntheticCircularSource:
    """Ships a fixed, synthetic corpus so the pipeline has something to run
    against without a live data source."""

    def fetch(self) -> tuple[dict, ...]:
        return SYNTHETIC_CIRCULARS


class CircularIngestionService:
    def __init__(self, source: CircularSource | None = None) -> None:
        self.source = source or SyntheticCircularSource()

    def ingest(self) -> tuple[Circular, ...]:
        raw = self.source.fetch()
        circulars = []
        for row in raw:
            obligations = extract_obligations(row["raw_text"])
            circulars.append(
                Circular(
                    id=row["id"],
                    title=row["title"],
                    category=row["category"],
                    issued_date=row["issued_date"],
                    obligations=obligations,
                )
            )
        return tuple(circulars)


SYNTHETIC_CIRCULARS: tuple[dict, ...] = (
    {
        "id": "CIR-2026-014",
        "title": "Disclosure norms for algorithmic trading by registered intermediaries",
        "category": "disclosure",
        "issued_date": "2026-06-02",
        "raw_text": (
            "Every registered intermediary offering algorithmic trading facilities "
            "shall disclose the algorithm approval status to the client before "
            "onboarding. Intermediaries must maintain an audit trail of every order "
            "generated by an approved algorithm for a minimum of five years. "
            "Any material change to an approved algorithm is required to be "
            "reported to the exchange within two working days. Failure to comply "
            "may attract a penalty and suspension of trading terminal access."
        ),
    },
    {
        "id": "CIR-2026-021",
        "title": "Revised KYC timelines for new demat account activations",
        "category": "kyc",
        "issued_date": "2026-06-18",
        "raw_text": (
            "Intermediaries shall complete KYC verification for new demat accounts "
            "within two working days of application. Physical verification is "
            "required to be replaced with video-based KYC wherever technically "
            "feasible. Any account not verified within the prescribed timeline "
            "must be flagged and reported in the monthly compliance report."
        ),
    },
    {
        "id": "CIR-2026-027",
        "title": "Reporting format for related-party transaction disclosures",
        "category": "reporting",
        "issued_date": "2026-06-25",
        "raw_text": (
            "Listed entities are required to submit related-party transaction "
            "disclosures in the revised XBRL format from the next reporting "
            "quarter. The disclosure format must include beneficial ownership "
            "details for all related parties above the materiality threshold."
        ),
    },
    {
        "id": "CIR-2026-030",
        "title": "Strengthening insider trading surveillance systems",
        "category": "surveillance",
        "issued_date": "2026-07-01",
        "raw_text": (
            "Every intermediary shall implement a surveillance system capable of "
            "flagging trades that precede unpublished price-sensitive information "
            "events. Suspicious trades must be reported to the exchange within "
            "twenty-four hours of detection. Non-reporting will be treated as a "
            "case of suspected insider trading and may attract a penalty."
        ),
    },
)
